directories:
  output: dist
  buildResources: build
  app: ./src
electronVersion: 22.3.9
electronDownload:
  version: 22.3.9+wvcus
  mirror: https://github.com/castlabs/electron-releases/releases/download/v
asar: true
productName: Quark Player
generateUpdatesFilesForAllChannels: false
appId: com.alex313031.quarkplayer
files:
  - filter:
      - '**/*'
extraFiles:
  - from: assets/icon64.png
  - from: assets/README.txt
linux:
  target:
    - zip
    - AppImage
    - deb
  maintainer: Alex313031
  vendor: Alex313031
  synopsis: Electron based Web Video Services Player. Supporting Netflix, Youtube, Twitch, Floatplane and More.
  category: Network;Browser;Media;AudioVideo;
  executableName: quark-player
  artifactName: quark-player_${version}_${arch}.${ext}
  desktop:
    Name: Quark Player
    StartupWMClass: quark-player
    Keywords: electron;netflix;media;
    Icon: quark-player
win:
  target:
    - zip
    - nsis
  publisherName: Alex313031
  executableName: quark_player
  artifactName: quark_player_win64_${version}_${arch}.${ext}
nsis:
  shortcutName: Quark Player
  artifactName: quark_player_setup_${version}_${arch}.${ext}
  deleteAppDataOnUninstall: false
  uninstallDisplayName: Quark Player ${version}
mac:
  category: public.app-category.navigation
